### ISSUE TITLE
Document not found as result of invoked Help

### ISSUE THREAD

**Issue by Ricky-Tigg** [gooselinux/system-config-users#1]
Component: system-config-users.noarch 1.3.8-6.fc29 @fedora

Invoking _Help_ results with message "_The URI ‘ghelp:system-config-users?s2-system-config-users-user-new#s2-system-config-users-user-new’ does not point to a valid page._"

**Comment by herlo** [comment]
This is just an old RPM config. WONTFIX, sorry.
