### ISSUE TITLE
To allow Enterprise login

### ISSUE THREAD

**Issue by Ricky-Tigg** [gooselinux/system-config-users#3]
Component: system-config-users.noarch 1.3.8-6.fc29 @fedora

Feature request: to allow **Enterprise** login.
Graphical implementation model:
![enterprise_login](https://user-images.githubusercontent.com/26058215/53487935-34137180-3a8d-11e9-8346-6a1477f73b73.png)

**Comment by herlo** [comment]
This is just an old RPM config. WONTFIX, sorry.
