### ISSUE TITLE
Section About – To update URL to maintener's page

### ISSUE THREAD

**Issue by Ricky-Tigg** [gooselinux/system-config-users#4]
Component: system-config-users.noarch 1.3.8-6.fc29 @fedora

Under section _About_, invoked present link – HTTP, an insecure protocol – to maintainer's page is redirected to a secure page – HTTPS, a secure protocol –. That URL would be worth to be updated.

![system-config-users_1 3 8_about_url-link](https://user-images.githubusercontent.com/26058215/53489019-40e59480-3a90-11e9-9984-e7febca229ca.png)

**Comment by herlo** [comment]
This is just an old RPM config. WONTFIX, sorry.
